### ISSUE TITLE
HTTP/Dubbo ip/url/错误获取解析

### ISSUE THREAD

**Issue by sunface** [origin-brain/rust-by-practice#111]

**Comment by congim** [comment]
![image](https://user-images.githubusercontent.com/10218415/57831072-b424ba00-77e6-11e9-96c1-900495b7c65a.png)

**Comment by congim** [comment]
![image](https://user-images.githubusercontent.com/10218415/57831129-d74f6980-77e6-11e9-94c9-363840cef9e9.png)

**Comment by congim** [comment]
![image](https://user-images.githubusercontent.com/10218415/57831280-4b8a0d00-77e7-11e9-86c6-53d46c41bd2b.png)

这里访问的ip地址被拒绝，但是pinpoint没有上报抓取到访问该ip的url
