### ISSUE TITLE
同一个异常出现两次

### ISSUE THREAD

**Issue by sunface** [origin-brain/rust-by-practice#14]
&{-1 adsfasdf.dasgfsdf.com} execute(org.apache.http.client.methods.HttpUriRequest request) H2
&{-1 adsfasdf.dasgfsdf.com} open(org.apache.http.conn.routing.HttpRoute route, org.apache.http.protocol.HttpContext context, org.apache.http.params.HttpParams params) H2

**Comment by congim** [comment]
异常通过代理跟踪的一个以上的方法向上传播到调用堆栈，则该异常也可能出现多次。 (传播过程中遇到的所有插件拦截器都会记录异常)
