### ISSUE TITLE
Add a success message for blocks that don't output anything

### ISSUE THREAD

**Issue by gtm-nayan** [origin-brain/rust-by-practice#144]
Take `basic types/numbers/2` for example, fixing it and running it makes the playground send "No output", which is slightly ambiguous. 

It'd be nice for exercises that show `No output` to include something like `println!("Success")` at the end so they'd show errors when there are any but show a clear `Success` message when it runs all the way through.

**Comment by sunface** [comment]
Wow, great idea ! You make a such good point here.

**Comment by sunface** [comment]
Done :)

**Comment by gtm-nayan** [comment]
Thanks!
