### ISSUE TITLE
why use * in method 6

### ISSUE THREAD

**Issue by zaq7434** [origin-brain/rust-by-practice#147]
the solutions is :
match *self {
        TrafficLightColor……
}

I think * can be removed.is there any special consideration?
in addition, TrafficLightColor can be replaced by Self?

**Comment by sunface** [comment]
Thanks for your feedback.

1.  I'm assuming you are reading the English version, then you can find the explanations [here - 6th exercise](https://practice.rs/compound-types/enum.html).

> `self` has type `&List`, and `*self` has type `List`, matching on a concrete type `T` is preferred over a match on a reference `&T` after Rust 2018 you can use self here and tail (with no ref) below as well, rust will infer &s and ref tail. 

2. Regarding your 2nd question, yeah `Self` is absolutely ok , but in my opinion,  `TrafficLightColor` is more clear, though it is somehow verbose.

**Comment by zaq7434** [comment]
Thinks for your serious answer! I need to continue to study RUST Course.
