### ISSUE TITLE
小勘误

### ISSUE THREAD

**Issue by tangdingga1** [origin-brain/rust-by-practice#149]
[位置](https://zh.practice.rs/compound-types/string.html#utf8_slice)

## 原文
```
use utf_slice;
```

## 正确
```
use utf8_slice;
```

<img width="856" alt="image" src="https://user-images.githubusercontent.com/37588992/157362166-b8fcecfa-e9f9-4c0c-b84c-abb4e7c6ab7a.png">

**Comment by sunface** [comment]
欢迎提交 pr :)

**Comment by tangdingga1** [comment]
> 欢迎提交 pr :)

好的。
我是觉得这个改动太小，不好意思提交pr。我现在提一个

**Comment by tangdingga1** [comment]
已提交[pr](https://github.com/sunface/rust-by-practice/pull/151/commits/eab24b80cec0081ae0d2f75e467ae61209f71909)

**Comment by sunface** [comment]
感谢，很细心～～为你点赞

**Comment by tangdingga1** [comment]
> 感谢，很细心～～为你点赞

谢谢你的书，写的太棒了！配合练习学习的效率真的很高，之前国内都没什么像样的`rust`相关学习资料。
