### ISSUE TITLE
统一每章练习的答案规范格式

### ISSUE THREAD

**Issue by mylvghb** [origin-brain/rust-by-practice#179]
建议：
1.  统一每个章节练习的答案统一格式；
2. 答案应链接到  `solutions` 里面相对于的 `xxx.md` 文件，而不是链接到 `solutions` 目录。

**Comment by sunface** [comment]
额。。我本来计划的是在写完练习题后，再排版进行再整理，包括但不限于:

- 题目的要求用 `/* */` 进行注释，跟普通的代码注释 `//` 区分

- 答案样式统一，链接整改

- 章节内增加合适的标题，帮助大家更好的在右侧目录进行导航

**Comment by mylvghb** [comment]
好的，期待ing

**Comment by sunface** [comment]
先关了～～
