### ISSUE TITLE
mdbook serve gives error

### ISSUE THREAD

**Issue by akhildevelops** [origin-brain/rust-by-practice#189]
I've cloned the repo and followed the steps mentioned in the README.md file to serve the book locally.

I ran below command from the root of the project.
`mdbook serve`

I get below errors:
```
2022-03-31 13:53:52 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/user/Projects/rust-by-practice/src" directory

2022-03-31 13:53:52 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

**Comment by akhildevelops** [comment]
If I run below command it works:
```
mdbook serve en/
```

**Comment by akhildevelops** [comment]
Lemme know. I can give a PR with updated command in README.md

**Comment by sunface** [comment]
You are right, the contents have been moved into the corresponding directories based on the language in which the book is written, please feel free to  submit a  PR :)

**Comment by akhildevelops** [comment]
Please review the PR

**Comment by sunface** [comment]
merged
