### ISSUE TITLE
An Editor for English

### ISSUE THREAD

**Issue by Tanish-Eagle** [origin-brain/rust-by-practice#197]
I'm willing to offer my time for editing the English text of Rust by Practice. I think I should inform you if you consider me, that it will be my first open source project.

Also, do tell whether it is a right place to talk about this or not.

**Comment by sunface** [comment]
Hello my friend, welcome to join.

I'm so happy finally this project has got an English editor, feel free to submit your first PR,  any types are welcomed :)

**Comment by Tanish-Eagle** [comment]
I will begin to work on it immediately tonight.

**Comment by sunface** [comment]
Great ! I'm so exciting and expecting.
