### ISSUE TITLE
询问一下文章构建的频率

### ISSUE THREAD

**Issue by KiyanYang** [origin-brain/rust-by-practice#326]
参考 [issue](https://github.com/sunface/rust-course/issues/1038)。

修复该问题已经有一段时间了，但是练习 https://zh.practice.rs/collections/String.html 里依旧是错误链接，所以想询问一下练习实践的构建频率。

**Comment by sunface** [comment]
抱歉，回复晚了，最近是只要拉到本地就更新一次，大概一周一次吧

**Comment by KiyanYang** [comment]
好的，谢谢回复
