### ISSUE TITLE
练习题本地搭建或者在线网站好像有点问题

### ISSUE THREAD

**Issue by cszyqqygxq** [origin-brain/rust-by-practice#488]
运行任意片段都提示 Playground Communication: Failed to fetch
![QQ截图20240104200026](https://github.com/sunface/rust-by-practice/assets/45395105/b04354c3-5808-4305-ab37-f9d8c969a4a4)

**Comment by Lartimes** [comment]
RustCourse 怎么出问题了？ 没域名了 为什么我这里404？

**Comment by sunface** [comment]
好的，我看看~~~
